# git
abbr -a g 'git'
abbr -a gd 'git diff'
abbr -a gco 'git checkout'
abbr -a vv 'git branches -vv'

abbr -a chex 'chmod +x'
abbr -a er 'echo_run'
abbr -a md 'mkdir -p'
abbr -a n 'nvim'
abbr -a rf 'rm -rfv'
abbr -a rl 'source ~/.config/fish/config.fish'
abbr -a s 'ls'
abbr -a cinnamon-restart 'cinnamon –replace -d :0.0> /dev/null 2>&1 &'
abbr -a unset 'set --erase'
