abbr -a chex 'chmod +x'
abbr -a g 'git'
abbr -a gco 'git checkout'
abbr -a md 'mkdir -p'
abbr -a rf 'rm -rfIv'
abbr -a rl 'source ~/.config/fish/config.fish'
abbr -a s 'ls'
abbr -a vv 'git branches -vv'
