imap jk <ESC>
imap kj <ESC>

so plug.vimrc

exec ":source $HOME" . "/rc/common/easymotion.vimrc"

" DetectIndent settings
augroup DetectIndent
  autocmd!
  autocmd BufReadPost * DetectIndent
augroup END

" Fugitive settings
if exists('s:fugitive_loaded')
  nnoremap <silent> <leader>gs  :<C-u>Gstatus<CR>
  nnoremap <silent> <leader>ga  :<C-u>Gwrite<CR>
  nnoremap <silent> <leader>gc  :<C-u>Gcommit<CR>
  nnoremap <silent> <leader>gps :<C-u>Gpush<CR>
  nnoremap <silent> <leader>gd  :<C-u>Gdiff<CR>
  nnoremap <silent> <leader>ghh :<C-u>Gdiff HEAD<CR>
  nnoremap <silent> <leader>gH  :<C-u>Gdiff HEAD<CR>
  nnoremap <silent> <leader>gh1 :<C-u>Gdiff HEAD~1<CR>
  nnoremap          <leader>gh  :<C-u>Gdiff HEAD~
  nnoremap <silent> <leader>gpc :<C-u>Git pc<CR>
  nnoremap <silent> <leader>gb  :<C-u>Gblame<CR>
  nnoremap <silent> <leader>gi  :<C-u>GEditIgnore<CR>
endif

" Save the state of folds on close and reload on launch.
au BufWinLeave * mkview
au BufWinEnter * silent loadview
